export const serviceData = [
  {
    name: "IT Service",
    iconPath: "/icon/it-service1.png",
    image: "/images/user/user-01.png",
    text: "The pre-built examples in this kit saved me weeks of development time. It’s a fantastic starting point for any AI SaaS project!",
    points: [
      "Server installation and configuration.",
      "Infrastructure planning and implementing.",
      "Remote access services.",
      "Exchange server configuration.",
      "Terminal server and client connectivity.",
      "Email server solutions for corporate.",
      "NAT solutions.",
    ],
  },
  {
    name: "CCTV Service",
    iconPath: "/icon/cctv1.png",
    image: "/images/user/user-02.png",
    text: "Building with OpenAI and Next.js has never been easier. The kit’s structure is intuitive and well-documented.",
    points: [
      "Digital video recording and clients installation.",
      "CCTV camera installation.",
      "Certification of CCTV projects.",
      "IP Camera Installation & Configuration.",
      "Remote Monitoring Setup (Mobile & PC Access).",
      "Upgrading Legacy CCTV Systems to HD/IP.",
      "Cloud Storage & Backup Solutions",
    ],
  },
  {
    name: "UI/UX Service",
    iconPath: "/icon/ui.png",
    image: "/images/user/user-03.png",
    text: "I was able to launch my AI startup in record time thanks to the pre-configured setup. Highly recommend!",
    points: [
      "Website Domain Purchase & Configuration.",
      "Graphics Design & Visual Content Creation.",
      "Web development.",
      "UI/UX Wireframing & Prototyping.",
      "User Journey Mapping & Persona Development.",
      "Brand Identity Design (Logo, Colors, Fonts).",
      "User Testing & Feedback Implementation.",
    ],
  },
  {
    name: "Networking Service",
    iconPath: "/icon/cloud-service1.png",
    image: "/images/user/user-04.png",
    text: "The flexibility of this kit is unmatched. It’s perfect for rapid prototyping and scaling AI applications.",
    points: [
      "Computer Assembling & Hardware Setup.",
      "System Troubleshooting & Diagnostics.",
      "Data Recovery & Backup Solutions.",
      "Regular System Servicing & Cleaning.",
      "LAN & WAN Network Setup.",
      "Firewall Installation & Network Security Setup.",
      "Server Installation & Maintenance.",
    ],
  },
  {
    name: "Bio-Metric Service",
    iconPath: "/icon/fingerprint1.png",
    image: "/images/user/user-05.png",
    text: "A game-changer for developers looking to integrate AI into their SaaS products. Clean code and great examples!",
    points: [
      "Annual Maintenance Contracts (AMC) for Servers, Workstations, Printers, and Plotters.",
      "Access Control System Installation & Configuration.",
      "PABX (Private Automatic Branch Exchange) Installation & Configuration.",
      "Biometric Time Attendance System Setup.",
      "Intercom & Paging System Installation.",
    ],
  },
];
