import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/HeaderFooter/Header";
import FloatingCall from "@/components/Others/FloatingCall";
import SocialMediaButton from "@/components/Others/FloatingIcons";
import Footer2 from "@/components/HeaderFooter/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer2 />
        <div className="fixed bottom-10 right-10 z-[1000]">
          <FloatingCall />
          <SocialMediaButton />
        </div>
      </body>
    </html>
  );
}
